### ISSUE TITLE
Inline Annotations not showing

### ISSUE THREAD

**Issue by gustavobittencourt** [kaste/PyTest#27]
Good evening, dear @kaste.

First, congrats for this amazing package!

I am using Sublime Text 3211 on macOS Catalina and the annotations are not showing when saving the test. The status bar color is changing correctly, and the screen seems blink when I save the file (I think it's visible in the gif I posted). I tried with different files, directories and projects, and it didn't work. The package options seems to be ok and just the defaults are active, so `"show_phantoms": true`. Any idea about what I can do?

Thank you in advance,

Gustavo

![screencapture](https://user-images.githubusercontent.com/7130975/70198401-899c3f00-16ed-11ea-9c75-0670d8156385.gif)

**Comment by kaste** [comment]
I noticed this is broken with newer py.test versions. I'll ship a new version.

**Comment by kaste** [comment]
v0.8.2 should fix this

Thanks for reporting.

**Comment by gustavobittencourt** [comment]
Thank you, @kaste!

And congratulations again for this amazing work!

**Comment by gustavobittencourt** [comment]
> v0.8.2 should fix this
> 
> Thanks for reporting.

Thank you, @kaste!

I just tested it and it's working correctly! However, the screen is still blinking twice everytime I save the file or call the runner. I tried with the option `apply_theme_tweaks` both true and false, but it's still happening. Is this the normal behavior or maybe it's something with my theme? I'm using *gruvbox*.

I'm sorry if this is the wrong place to post this question. I can open a new issue if it's necessary.

Thank you again and best regards!

**Comment by kaste** [comment]
The screen is blinking?  In the gif I see the screen goes blank or black. Do you mean that or something different?

**Comment by gustavobittencourt** [comment]
Indeed it's not really blinking, it's what you said: every time I send the 'run test' command it goes black and then back to normal (sometimes it does it twice in a row).

![Gravação de Tela 2019-12-06 às 22 01 18](https://user-images.githubusercontent.com/7130975/70366529-c5aedb80-1876-11ea-96b6-076d2dbe19fa.gif)

**Comment by kaste** [comment]
That's super annoying.  It looks like as if the computer or setup is not fast enough to do a fast redraw.  Honestly I would first try a different theme, I never had that tbh even in battery mode on a rather slow computer.  Since the status bar goes from black to green or red and then back to the original color t.i. it redraws twice it sound reasonable to see two "blinks". However, as I said I never had graphic or any other performance issues with Sublime. (I also don't tell Sublime to draw the status bar in a different color, I only set a state flag and Sublime then applies that automatically.) 

Usually the guys in the official Sublime forum know a lot more about that stuff, and they maybe know if some theme is wasteful and could actually slow down Sublime.

**Comment by gustavobittencourt** [comment]
Hi @kaste! 

You are so considerable! Thank you!

I made a fresh Sublime reinstall to test how different themes were influencing the plugin, so maybe this can give you some insight. The only theme that worked "correctly" in my machine was the default, i.e., the status bar and syntax were changing colors without blinking.
![Default Theme - Status e Syntax, sem piscar](https://user-images.githubusercontent.com/7130975/70575841-14fe5000-1b86-11ea-972f-fdce6dcd4cce.gif)

On the other themes, either the status bar did not change its color, or the screen flickered at the time of this change. As all the other plugins were uninstalled, Sublime was performing faster and, consequently, the flickering were quicker. Also, this seems to be independent of the annotations formating (it depends on the UI color scheme, not on the theme).

- Themes that didn't change the status bar color but also didn't flickered:
   - Adaptive ![Adaptive - Só Syntax, sem piscar](https://user-images.githubusercontent.com/7130975/70576179-082e2c00-1b87-11ea-9e06-e2bd3554eeb0.gif)

   - Agila ![Agila - Só Syntax, sem piscar](https://user-images.githubusercontent.com/7130975/70576137-e765d680-1b86-11ea-9d3f-0079ae6b327e.gif)

- Themes that changed the status bar but flickered:
   - Ayu ![Ayu - Só status, piscando rápido](https://user-images.githubusercontent.com/7130975/70576201-11b79400-1b87-11ea-8ad8-5e187e7779e1.gif)

   - Gruvbox ![Gruvbox - Status e Syntax, piscando duas vezes](https://user-images.githubusercontent.com/7130975/70576204-1419ee00-1b87-11ea-843d-2b7579bd1b12.gif)

My setup was:
- MacBook Pro (15-inch, 2017) with macOS Catalina 10.15.1
- 2,9 GHz Intel Core i7 Quad-Core
- 16 GB 2133 MHz LPDDR3
- Intel HD Graphics 630 1536 MB
- Sublime Text 3 (Build 3211)
- Just `Package Manager `, the themes and `Pytest` installed as plugins

If there is anything else I can help you with, count on me!

Best regards,

Gustavo

**Comment by kaste** [comment]
On a fresh install, I only tested "Ayu" which just works on my computer.  I'm on Windows 10 with a sloppy laptop, not comparable to your machine.  But you don't need super-power to colorize a statusbar either.  There is probably something with your system, Sublime setup that it falls back to a "sloppy" rendering method.  (Have you seen the `"gpu_window_buffer": "auto",` setting in the Sublime preferences?)  This is best to be asked in the Sublime forum, they also help if you didn't pay for the software.

**Comment by gustavobittencourt** [comment]
You nailed it, @kaste. The problem was with the `gpu_window_buffer`. I set it to false and the flickering problem was solved, but Sublime became unusable (extremely slow) 😕Thus, I don't think there is gonna be any solution, but I'll try to ask in their forum.

Regards!
